<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>ma_links</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Migration.Common.Log\Migration.Common.Log.csproj" />
    <ProjectReference Include="..\Migration.Common\Migration.Common.csproj" />
  </ItemGroup>

</Project>
